### ISSUE TITLE
Improve README.md

### ISSUE THREAD

**Issue by jcruz** [cs121-team-panda/coconut-interpreter#66]
- [x] Installation instructions
- [x] How to run
- [x] Update features (i.e. Python switch, updated error messages, etc.)

**Comment by brittanywang** [comment]
For installation instruction and how to run, show I be more specific in the README.md? Like 'go to the link:  https://cs121-team-panda.github.io/coconut-interpreter/ to try the current version' and 'click the run button to execute code'

**Comment by jcruz** [comment]
embedding app docs in react repo https://github.com/cs121-team-panda/coconut-interpreter-react/blob/master/docs/Embed.md

**Comment by nkadonaga** [comment]
- [ ] Use template as required by [handoff meeting preparation Canvas assignment](https://canvas.instructure.com/courses/1269330/assignments/7799436)
